spring.application.name=video-game-db

spring.config.import=optional:file:.env[.properties]

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true

spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

igdb.client-id=${TWITCH_CLIENT_ID}
igdb.client-secret=${TWITCH_CLIENT_SECRET}
igdb.twitch-token-uri=https://id.twitch.tv/oauth2/token
igdb.token-refresh-buffer=60s
